name: schema2model
description: Generate strongly typed Dart models from JSON Schema documents.
version: 1.0.0
repository: https://github.com/kingwill101/schema2model
issue_tracker: https://github.com/kingwill101/schema2model/issues

environment:
  sdk: ^3.9.2

dependencies:
  build: ^2.4.1
  glob: ^2.1.2
  collection: ^1.19.0
  meta: ^1.11.0
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.4.11
  test: ^1.25.6
